# .github/workflows/test.yml
name: Python Unit Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8=7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest

    - name: Run tests
      run: python -m unittest discover -s . -p "test_*.py"
